import global_variables 
simulation = open('simulation.py', 'w')
simulation.write('import ccm\nfrom ccm.lib.actr import *\nimport global_variables\nlog=ccm.log()\nclass MyEnvironment(ccm.Model):\n    pass\nclass MyAgent(ACTR):\n') 
simulation.write('	new_actions='+str(global_variables.new_actions)+'#all unique possible actions \n  ') 
simulation.write('	action_stream='+str(global_variables.action_stream)+'#all actions by the user\n  ') 
simulation.write('	fired_actions = {}\n	chunk_activations = {}\n	focus = Buffer()\n	DMBuffer = Buffer()\n')
simulation.write("""	DM = Memory(DMBuffer,latency=0.05,threshold=0.5)\n	dm_n = DMNoise(DM,noise=0.0,baseNoise=0.0)\n	dm_bl = DMBaseLevel(DM,decay=0.5,limit=None)\n	def init():\n		focus.set('action_0')\n """)

for i,x in enumerate(global_variables.action_stream) :
	simulation.write('\n')
	simulation.write("""	def action_"""+str(i)+ """(focus='action_"""+str(i)+"""'):\n		countHelper = -1\n """)
	simulation.write('		if (action_stream[len(fired_actions)] in new_actions) :\n ')
	simulation.write('			new_actions.remove(action_stream[len(fired_actions)])\n ')
	simulation.write("""			dmstring = 'action_"""+str(i)+""":' + action_stream[len(fired_actions)]\n """)
	simulation.write('			fired_actions[action_stream[len(fired_actions)]]= str(len(fired_actions))\n')
	simulation.write('			DM.add(dmstring)\n')
	simulation.write("""			focus.set('action_' + str(len(fired_actions)))\n""")
	simulation.write('		else :\n')
	simulation.write('			countHelper = 0\n')
	simulation.write("""			dmstring = 'action_' + fired_actions[action_stream[len(fired_actions)]] + ':?action'\n""")
	simulation.write('			DM.request(dmstring)\n')
	simulation.write("""			focus.set('action_' + fired_actions[action_stream[len(fired_actions)]] + '_')\n""")
	simulation.write("""		list_of_chunks = self.DM.find_matching_chunks('')\n""")
	simulation.write("""		actions_temp = [str(n).split(':')[0] for n in list_of_chunks]\n""")
	simulation.write('		chunk_activations[str(len(fired_actions)+countHelper)] = {}\n')
	simulation.write('		for n,chunk in enumerate(list_of_chunks):\n')
	simulation.write('			chunk_activations[str(len(fired_actions)+countHelper)][str(chunk[actions_temp[n]])] = str(round(self.DM.get_activation(chunk), 3))\n')
	simulation.write('\n')
	simulation.write("""	def forgot_"""+str(i)+"""(focus='action_"""+str(i)+"""_', DMBuffer=None, DM='error:True'):\n""")
	simulation.write("""		focus.set('stop')\n""")
	simulation.write('\n')
	simulation.write("""	def remember_"""+str(i)+"""(focus='action_"""+str(i)+"""_', DMBuffer="action_"""+str(i)+""":?action"):\n""")
	simulation.write("""		print "I remember action_"""+str(i)+""":",action\n""")
	simulation.write('		fired_actions[action_stream[len(fired_actions)]]= str(len(fired_actions))\n')
	simulation.write("""		fired_actions['dummy_"""+str(i)+"""'] = action_stream[len(fired_actions)]\n""")
	simulation.write("""		focus.set('action_' + str(len(fired_actions)))\n""")
	simulation.write('\n')

simulation.write("""	def action_"""+str(len(global_variables.action_stream))+"""(focus='action_"""+str(len(global_variables.action_stream))+"""'): \n""")
simulation.write("""		focus.set('stop')\n""")
simulation.write("""	def stop_production(focus='stop'):\n""")
simulation.write('		self.stop()\n')
simulation.write('\ntim=MyAgent()\nsubway=MyEnvironment()\nsubway.agent=tim\nccm.log_everything(subway) \nsubway.run() \nglobal_variables.chunk_activations = tim.chunk_activations \nccm.finished()')



simulation.close()  